JRCodn/Worth-It

app/controllers/pages_controller.rb
app/services/up_api.rb
app/views/pages/transactions.html.erb

- Added the accounts showing up on the Transactions Page
- Updated the controller so that it would work.

added account surfacing on the transactions page

---

app/controllers/goals_controller.rb
app/controllers/pages_controller.rb
app/controllers/reasons_controller.rb
app/models/goal.rb
app/models/reason.rb
app/views/pages/_goals_builder.html.erb
app/views/pages/dashboard.html.erb

- Created the reasons controller
- Created a simple form for the goal builder
- Nested reasons for saving under goals
- Added free text to reasons why you're saving

Reasons controller

---

app/services/up_api.rb
db/schema.rb

refactored api call to a method

refactored api call to a method

---

app/services/up_api.rb

basic error handling for api, much work to do

---

app/javascript/packs/application.js
app/javascript/packs/purchase_creator.js
app/views/pages/_calculator_builder.html.erb
app/views/pages/dashboard.html.erb

Built purchase create to enable users to input something they want to buy (purchase) and how much it costs
Built straw-man calculator to determine impact of the purchase on a) how long it will take to achieve their goal and b) referring back to the user's reasons for savings
(^This has been built without the weekly contribution and savings goal being pulled from API, will adjust accordingly later)

Calculator services

---

app/javascript/packs/goal_saver.js
app/javascript/packs/init_flatpickr.js
app/views/pages/_goals_builder.html.erb
package.json
yarn.lock

- added weekly contributions function

Added weekly contributions to dashboard

---

app/javascript/packs/goal_saver.js
app/javascript/packs/purchase_creator.js

- Fixed javascript trying load on every page

fixed some javascript errors trying to load on wrong pages

---

app/views/pages/_goals_builder.html.erb

added tag to id

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/pages/_calculator_builder.scss
app/javascript/packs/goal_saver.js
app/javascript/packs/purchase_creator.js
app/views/pages/_calculator_builder.html.erb
app/views/pages/dashboard.html.erb
package.json
yarn.lock

Updated the purchase creator and randomized the contextual spend (eg. pizza, coffee, avo, etc...)

Contextualize purchase

---

app/views/pages/_goal_summary.html.erb
app/views/pages/dashboard.html.erb

- Moved some code from dashboard to goals_summary partial

Added some code from dashboard to goals_summary partial

---

app/controllers/goals_controller.rb
app/models/user.rb
app/services/up_api.rb

-Added validation for the api key on sign up to make sure api keys will work.

Check api on signup

---

app/javascript/packs/goal_saver.js
app/views/pages/goal_builder.html.erb
yarn.lock

-Added placeholder to goal builder

Added place holder to goal builder form

---

.gitignore
app/javascript/packs/purchase_creator.js
app/views/pages/_goal_summary.html.erb
app/views/pages/calculator.html.erb
app/views/shared/_navbar.html.erb
config/environments/env.

- Added name, description, due date to calculator
- Amended copy/front-end text containers

[Did not amend homepage] Fixed calculator to pull goal details onto calculator page and front-end amendments

---

app/assets/stylesheets/config/_colors.scss
app/controllers/pages_controller.rb
app/views/pages/dashboard.html.erb
config/routes.rb

- Added back Toms changes that I reverted commit to check on a bug.

Hopefully fixed a revert

---

app/javascript/packs/goal_saver.js
app/javascript/packs/init_flatpickr.js
app/views/shared/_navbar.html.erb

-Added a eventlistener for turbo link to javascript pages to allow functions to work on page load.

Added event listener to allow javasript to work on page load

---

app/views/pages/_goals_builder.html.erb
app/views/shared/_navbar.html.erb
yarn.lock

-Trying to fix flatpickr breaking on heroku

removed lottie to hopefully fix flatpickr breaking in heroku

---

app/assets/stylesheets/application.scss
app/javascript/packs/application.js
app/javascript/packs/init_flatpickr.js

- Trying to fix bug with flatpickr on heroku.

Trying to add flatpickr on production

---

app/javascript/packs/application.js
app/javascript/packs/goal_saver.js

-Made goal_saver in to a function.

Made goal_saver.js into a function

---

app/assets/stylesheets/application.scss

-took out .css for flatpickr in application.scss

Minor change to fix flatpickr on heroku again

---

app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_calculator_builder.scss
app/javascript/packs/purchase_creator.js
app/views/pages/_calculator_builder.html.erb
app/views/pages/calculator.html.erb

Made an edit to the calculator page using UP banking elements.

Worth it calc

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/pages/_dashboard.scss
app/helpers/contribution_helper.rb
app/views/pages/_goal_summary.html.erb
app/views/pages/dashboard.html.erb

- Worked on dashboard to look like UP
- updated the contribution helper so we could have the percentage bar
- updated application.scss

Updated dashboard designs to look like UP

---

app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_calculator_builder.scss
app/controllers/application_controller.rb
app/javascript/packs/purchase_creator.js
app/views/devise/registrations/new.html.erb
app/views/pages/_calculator_builder.html.erb
app/views/pages/calculator.html.erb
app/views/shared/_navbar.html.erb
db/migrate/20210729084830_add_first_name_to_users.rb
db/schema.rb

Added more design to the calculator builder and added a first name column to the user model.

designed calc builder and added firstname to user

---

app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

Hey guys,
Just added that UP style linear gradient to the homepage, added the product name/value prop/proof points.
Please amend as you see fit (bit squished so might not have room for the frames...will revisit).
Thanks,
Vic

Added text/background to homepage

---

app/views/pages/_goal_summary.html.erb

Calcpagekt

---

app/helpers/contribution_helper.rb
app/views/pages/_due_date.html.erb

- Made a partial page to have a progress bar come up on goal summary
- Added an extra method in contribution helper

Added a progess bar for the due date

---

app/assets/stylesheets/pages/_calculator_builder.scss
app/javascript/packs/purchase_creator.js
app/views/pages/_goal_summary.html.erb
app/views/pages/calculator.html.erb

Edited the calc builder page and included the IF statement in javascript

Calcpagefrontend

---

app/assets/stylesheets/application.scss
app/views/devise/registrations/new.html.erb
app/views/pages/_due_date.html.erb
app/views/pages/goal_builder.html.erb

-Made some simple changes to goal_builder front

made some basic changes to front end on goal_builder page

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/pages/_form_styling.scss
app/assets/stylesheets/pages/_goal_builder.scss
app/views/pages/goal_builder.html.erb

-Changed styling on goal builder page

Done some more front end on goal builder

---

app/helpers/contribution_helper.rb
app/views/pages/_due_date.html.erb

- Fixed progress bar calculation for due date.

Fixed due date progress bar

---

app/helpers/contribution_helper.rb
app/javascript/packs/goal_saver.js
app/views/pages/_due_date.html.erb
app/views/pages/goal_builder.html.erb

- Added comments to a few pages for future me and anyone else reading

Added comments to a couple of pages

---

app/assets/stylesheets/pages/_home.scss
app/javascript/packs/progress_bar.js

Fixed navbar background

---

app/views/shared/_navbar.html.erb

Added sign in button if no user signed in

---

app/views/shared/_navbar.html.erb

changed the colour of text in login

Changed colour of login text

---

app/javascript/packs/progress_bar.js
app/views/pages/_due_date.html.erb
package-lock.json

-Added animation to date progress bar.

Added date prog bar animation

---

app/assets/stylesheets/pages/_form_styling.scss
app/assets/stylesheets/pages/_goal_builder.scss
app/views/pages/_goal_builder_quotes.html.erb
app/views/pages/goal_builder.html.erb

-Made some minor changes to goal builder page fe and added quotes.

Made minor changes to fe of goal builder and added quotes.

---

app/assets/stylesheets/pages/_calculator_builder.scss
app/javascript/packs/purchase_creator.js
app/views/pages/calculator.html.erb

- Fixed the calc inputs.
- Updated the copy for less than 7 days results
- Re-align the bullet points

Calc fixes
